# Generated by Django 3.1.5 on 2021-02-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=45)),
                ('n_nota', models.CharField(max_length=45)),
                ('market', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField()),
                ('total_mov', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('total_liq', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tx_bovespa', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tx_liquida', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tx_registro', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('corretagem', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('outros', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='uploads/notas/')),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ('date',),
            },
        ),
    ]
