# Generated by Django 3.1.5 on 2021-01-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=45)),
                ('symbol', models.CharField(blank=True, max_length=45, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('isin', models.CharField(blank=True, max_length=45, null=True)),
                ('classe', models.CharField(blank=True, max_length=45, null=True)),
                ('market_cod', models.CharField(blank=True, max_length=45, null=True)),
                ('market', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('setor', models.CharField(blank=True, max_length=45, null=True)),
                ('subsetor', models.CharField(blank=True, max_length=45, null=True)),
                ('segmento', models.CharField(blank=True, max_length=45, null=True)),
                ('codcvm', models.CharField(blank=True, max_length=15, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=45, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj_adm', models.CharField(blank=True, max_length=45, null=True)),
                ('razao_social_adm', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ('sigla',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amont', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('commission', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('nota_id', models.CharField(blank=True, max_length=15, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='core.asset')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ('date',),
            },
        ),
    ]
