# Generated by Django 3.1.5 on 2021-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_transaction_amont'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amont',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
