# Generated by Django 3.1.5 on 2021-01-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_obs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='nome',
            new_name='name',
        ),
    ]
