# Generated by Django 3.1.5 on 2021-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('sigla', models.CharField(max_length=45, primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isin', models.CharField(blank=True, max_length=45, null=True)),
                ('classe', models.CharField(blank=True, max_length=45, null=True)),
                ('market_cod', models.CharField(blank=True, max_length=45, null=True)),
                ('market', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('setor', models.CharField(blank=True, max_length=45, null=True)),
                ('subsetor', models.CharField(blank=True, max_length=45, null=True)),
                ('segmento', models.CharField(blank=True, max_length=45, null=True)),
                ('codcvm', models.CharField(blank=True, max_length=15, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=45, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj_adm', models.CharField(blank=True, max_length=45, null=True)),
                ('razao_social_adm', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ('sigla',),
            },
        ),
    ]
